apiVersion: v1
kind: Secret
metadata:
  name: booking-db-secret
  namespace: movie-app
type: Opaque
data:
  POSTGRES_DB: Ym9va2luZ19kYg==
  POSTGRES_USER: Ym9va2luZ191c2Vy
  POSTGRES_PASSWORD: Ym9va2luZ19wYXNz
