apiVersion: v1
kind: Secret
metadata:
  name: movie-db-secret
  namespace: movie-app
type: Opaque
data:
  POSTGRES_DB: bW92aWVfZGI=
  POSTGRES_USER: bW92aWVfdXNlcg==
  POSTGRES_PASSWORD: bW92aWVfcGFzcw==
